---
- name: Configure Virtual Host
  hosts: managed-1
  pre_tasks:
          - name: pre_tasks message
            debug:
                    msg: 'Make Web server configuration'

  roles:
          - role: myvhost
            tcpport: 80


  post_tasks:
          - name: create dir '/var/www/vhosts/{{ ansible_hostname }}/'
            file:
                    state: directory
                    path: '/var/www/vhosts/{{ ansible_hostname }}/'

          - name: HTML content is installed
            copy:
                    src: files/index.html
                    dest: '/var/www/vhosts/{{ ansible_hostname }}/'

          - name: post_tasks message
            debug:
                    msg: 'Web server is configured'

...
