- name: play
  hosts: localhost
  gather_facts: false
  vars:
          webpkg:
            CentOS:
                package: httpd
            Ubuntu:
                package: apache2
            openSUSE Leap:
                package: httpd
  tasks:
          - name: show hash
            debug:
                    msg: '{{ webpkg[distro].package }}'
