---
# tasks file for myvhost
- name: Install Apache
  package:
          name: httpd
          state: latest

- name: Start/Enable Apache
  service:
          name: httpd
          state: started
          enabled: true

- name: Install vhost configuration file
  template:
          src: vhost.conf.j2
          dest: /etc/httpd/conf.d/vhost.conf
          owner: root
          group: root
          mode: 0644
  notify: restart httpd
