---
- name: Install apache web server on CentOS/SUSE
  package:
          name: '{{ webpkg[ansible_distribution].package }}'
          state: present

- name: Install firewalld
  package:
          name: firewalld
          state: present

- name: Start/Enable firewalld
  service:
          name: firewalld
          state: started
          enabled: true

- name: Allow traffic through port 80
  firewalld:
          service: http
          state: enabled
          permanent: true
          immediate: true

- name: Start/Enable web server on CentOS
  service:
          name: '{{ webpkg[ansible_distribution].service }}'
          state: started
          enabled: true

          #- name: Endure directory /var/www/html is there
          #  file:
          #          path: /var/www/html
          #          state: directory

- name: Copy index.html into destination /var/www/html
  template:
          src: index.j2
          dest: '{{ webpkg[ansible_distribution].docroot }}/index.html'
          mode: 0644
          owner: root
          group: root
  notify: restart webserver
