---
- name: Install apache web server on CentOS/SUSE
  package:
          name: '{{ webconf[ansible_distribution].package }}'
          state: present

- name: Install firewalld
  package:
          name: firewalld
          state: present

- name: Start/Enable firewalld
  service:
          name: firewalld
          state: started
          enabled: true

- name: Allow traffic through port 80
  firewalld:
          service: http
          state: enabled
          permanent: true
          immediate: true

- name: Create directories
  file:
          path: '{{ item }}'
          state: directory
          mode: 0755
          group: root
          owner: root
  loop:
          - '{{ webconf[ansible_distribution].wwwroot }}'
          - '{{ webconf[ansible_distribution].docroot }}'
          - '{{ webconf[ansible_distribution].cgibinroot }}'

- name: Install apache configuration file
  template:
          src: '{{ webconf[ansible_distribution].src_confile }}'
          dest: '{{ webconf[ansible_distribution].confile }}'
  notify: restart webserver

- name: Creating remote index.html
  template:
          src: index.j2
          dest: '{{ webconf[ansible_distribution].docroot }}/index.html'
          mode: 0644
          owner: root
          group: root

- name: Start/Enable web server
  service:
          name: '{{ webconf[ansible_distribution].service }}'
          state: started
          enabled: true
